baseURL = 'https://example.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = '我的博客'
theme = 'svn-retro'

[params]
  tagline = ''
  description = ''

[pagination]
  pagerSize = 20

[permalinks]
  posts = '/posts/:slug/'
