baseURL = 'https://nc.gy/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = "Networkcat's Blog"
theme = 'svn-retro'

[params]

[pagination]
  pagerSize = 20

[permalinks]
  posts = '/posts/:slug/'
